/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables.records;


import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;
import org.northcoder.sakila.jooq.tables.SalesByStoreTable;
import org.northcoder.sakila.jooq.tables.pojos.SalesByStore;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SalesByStoreRecord extends TableRecordImpl<SalesByStoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.sales_by_store.store</code>.
     */
    public void setStore(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.sales_by_store.store</code>.
     */
    public String getStore() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sakila.sales_by_store.manager</code>.
     */
    public void setManager(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.sales_by_store.manager</code>.
     */
    public String getManager() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sakila.sales_by_store.total_sales</code>.
     */
    public void setTotalSales(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.sales_by_store.total_sales</code>.
     */
    public BigDecimal getTotalSales() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalesByStoreRecord
     */
    public SalesByStoreRecord() {
        super(SalesByStoreTable.SALES_BY_STORE);
    }

    /**
     * Create a detached, initialised SalesByStoreRecord
     */
    public SalesByStoreRecord(String store, String manager, BigDecimal totalSales) {
        super(SalesByStoreTable.SALES_BY_STORE);

        setStore(store);
        setManager(manager);
        setTotalSales(totalSales);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SalesByStoreRecord
     */
    public SalesByStoreRecord(SalesByStore value) {
        super(SalesByStoreTable.SALES_BY_STORE);

        if (value != null) {
            setStore(value.store());
            setManager(value.manager());
            setTotalSales(value.totalSales());
            resetChangedOnNotNull();
        }
    }
}
