/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.northcoder.sakila.jooq.tables.StoreTable;
import org.northcoder.sakila.jooq.tables.pojos.Store;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StoreRecord extends UpdatableRecordImpl<StoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.store.store_id</code>.
     */
    public void setStoreId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.store.store_id</code>.
     */
    public Integer getStoreId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sakila.store.manager_staff_id</code>.
     */
    public void setManagerStaffId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.store.manager_staff_id</code>.
     */
    public Integer getManagerStaffId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sakila.store.address_id</code>.
     */
    public void setAddressId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.store.address_id</code>.
     */
    public Integer getAddressId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sakila.store.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>sakila.store.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreRecord
     */
    public StoreRecord() {
        super(StoreTable.STORE);
    }

    /**
     * Create a detached, initialised StoreRecord
     */
    public StoreRecord(Integer storeId, Integer managerStaffId, Integer addressId, LocalDateTime lastUpdate) {
        super(StoreTable.STORE);

        setStoreId(storeId);
        setManagerStaffId(managerStaffId);
        setAddressId(addressId);
        setLastUpdate(lastUpdate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised StoreRecord
     */
    public StoreRecord(Store value) {
        super(StoreTable.STORE);

        if (value != null) {
            setStoreId(value.storeId());
            setManagerStaffId(value.managerStaffId());
            setAddressId(value.addressId());
            setLastUpdate(value.lastUpdate());
            resetChangedOnNotNull();
        }
    }
}
