/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public record Staff(
    Integer staffId,
    String firstName,
    String lastName,
    Integer addressId,
    byte[] picture,
    String email,
    Integer storeId,
    Byte active,
    String username,
    String password,
    LocalDateTime lastUpdate
) implements Serializable {

    private static final long serialVersionUID = 1L;

}
