/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;
import org.northcoder.sakila.jooq.tables.ActorInfoTable;
import org.northcoder.sakila.jooq.tables.pojos.ActorInfo;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActorInfoRecord extends TableRecordImpl<ActorInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.actor_info.actor_id</code>.
     */
    public void setActorId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.actor_info.actor_id</code>.
     */
    public Integer getActorId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sakila.actor_info.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.actor_info.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sakila.actor_info.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.actor_info.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sakila.actor_info.film_info</code>.
     */
    public void setFilmInfo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sakila.actor_info.film_info</code>.
     */
    public String getFilmInfo() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActorInfoRecord
     */
    public ActorInfoRecord() {
        super(ActorInfoTable.ACTOR_INFO);
    }

    /**
     * Create a detached, initialised ActorInfoRecord
     */
    public ActorInfoRecord(Integer actorId, String firstName, String lastName, String filmInfo) {
        super(ActorInfoTable.ACTOR_INFO);

        setActorId(actorId);
        setFirstName(firstName);
        setLastName(lastName);
        setFilmInfo(filmInfo);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ActorInfoRecord
     */
    public ActorInfoRecord(ActorInfo value) {
        super(ActorInfoTable.ACTOR_INFO);

        if (value != null) {
            setActorId(value.actorId());
            setFirstName(value.firstName());
            setLastName(value.lastName());
            setFilmInfo(value.filmInfo());
            resetChangedOnNotNull();
        }
    }
}
