/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.northcoder.sakila.jooq.tables.FilmTextTable;
import org.northcoder.sakila.jooq.tables.pojos.FilmText;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilmTextRecord extends UpdatableRecordImpl<FilmTextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.film_text.film_id</code>.
     */
    public void setFilmId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.film_text.film_id</code>.
     */
    public Integer getFilmId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sakila.film_text.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.film_text.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sakila.film_text.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.film_text.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmTextRecord
     */
    public FilmTextRecord() {
        super(FilmTextTable.FILM_TEXT);
    }

    /**
     * Create a detached, initialised FilmTextRecord
     */
    public FilmTextRecord(Integer filmId, String title, String description) {
        super(FilmTextTable.FILM_TEXT);

        setFilmId(filmId);
        setTitle(title);
        setDescription(description);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FilmTextRecord
     */
    public FilmTextRecord(FilmText value) {
        super(FilmTextTable.FILM_TEXT);

        if (value != null) {
            setFilmId(value.filmId());
            setTitle(value.title());
            setDescription(value.description());
            resetChangedOnNotNull();
        }
    }
}
