/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.northcoder.sakila.jooq.tables.RentalTable;
import org.northcoder.sakila.jooq.tables.pojos.Rental;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RentalRecord extends UpdatableRecordImpl<RentalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.rental.rental_id</code>.
     */
    public void setRentalId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.rental.rental_id</code>.
     */
    public Integer getRentalId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sakila.rental.rental_date</code>.
     */
    public void setRentalDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.rental.rental_date</code>.
     */
    public LocalDateTime getRentalDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sakila.rental.inventory_id</code>.
     */
    public void setInventoryId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.rental.inventory_id</code>.
     */
    public Integer getInventoryId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sakila.rental.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sakila.rental.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sakila.rental.return_date</code>.
     */
    public void setReturnDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>sakila.rental.return_date</code>.
     */
    public LocalDateTime getReturnDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>sakila.rental.staff_id</code>.
     */
    public void setStaffId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>sakila.rental.staff_id</code>.
     */
    public Integer getStaffId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>sakila.rental.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>sakila.rental.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RentalRecord
     */
    public RentalRecord() {
        super(RentalTable.RENTAL);
    }

    /**
     * Create a detached, initialised RentalRecord
     */
    public RentalRecord(Integer rentalId, LocalDateTime rentalDate, Integer inventoryId, Integer customerId, LocalDateTime returnDate, Integer staffId, LocalDateTime lastUpdate) {
        super(RentalTable.RENTAL);

        setRentalId(rentalId);
        setRentalDate(rentalDate);
        setInventoryId(inventoryId);
        setCustomerId(customerId);
        setReturnDate(returnDate);
        setStaffId(staffId);
        setLastUpdate(lastUpdate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RentalRecord
     */
    public RentalRecord(Rental value) {
        super(RentalTable.RENTAL);

        if (value != null) {
            setRentalId(value.rentalId());
            setRentalDate(value.rentalDate());
            setInventoryId(value.inventoryId());
            setCustomerId(value.customerId());
            setReturnDate(value.returnDate());
            setStaffId(value.staffId());
            setLastUpdate(value.lastUpdate());
            resetChangedOnNotNull();
        }
    }
}
