/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.northcoder.sakila.jooq.Indexes;
import org.northcoder.sakila.jooq.Keys;
import org.northcoder.sakila.jooq.Sakila;
import org.northcoder.sakila.jooq.tables.CityTable.CityPath;
import org.northcoder.sakila.jooq.tables.CustomerTable.CustomerPath;
import org.northcoder.sakila.jooq.tables.StaffTable.StaffPath;
import org.northcoder.sakila.jooq.tables.StoreTable.StorePath;
import org.northcoder.sakila.jooq.tables.records.AddressRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AddressTable extends TableImpl<AddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sakila.address</code>
     */
    public static final AddressTable ADDRESS = new AddressTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AddressRecord> getRecordType() {
        return AddressRecord.class;
    }

    /**
     * The column <code>sakila.address.address_id</code>.
     */
    public final TableField<AddressRecord, Integer> ADDRESS_ID = createField(DSL.name("address_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sakila.address.address</code>.
     */
    public final TableField<AddressRecord, String> ADDRESS_ = createField(DSL.name("address"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>sakila.address.address2</code>.
     */
    public final TableField<AddressRecord, String> ADDRESS2 = createField(DSL.name("address2"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>sakila.address.district</code>.
     */
    public final TableField<AddressRecord, String> DISTRICT = createField(DSL.name("district"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>sakila.address.city_id</code>.
     */
    public final TableField<AddressRecord, Integer> CITY_ID = createField(DSL.name("city_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sakila.address.postal_code</code>.
     */
    public final TableField<AddressRecord, String> POSTAL_CODE = createField(DSL.name("postal_code"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>sakila.address.phone</code>.
     */
    public final TableField<AddressRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>sakila.address.last_update</code>.
     */
    public final TableField<AddressRecord, LocalDateTime> LAST_UPDATE = createField(DSL.name("last_update"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private AddressTable(Name alias, Table<AddressRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AddressTable(Name alias, Table<AddressRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sakila.address</code> table reference
     */
    public AddressTable(String alias) {
        this(DSL.name(alias), ADDRESS);
    }

    /**
     * Create an aliased <code>sakila.address</code> table reference
     */
    public AddressTable(Name alias) {
        this(alias, ADDRESS);
    }

    /**
     * Create a <code>sakila.address</code> table reference
     */
    public AddressTable() {
        this(DSL.name("address"), null);
    }

    public <O extends Record> AddressTable(Table<O> path, ForeignKey<O, AddressRecord> childPath, InverseForeignKey<O, AddressRecord> parentPath) {
        super(path, childPath, parentPath, ADDRESS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AddressPath extends AddressTable implements Path<AddressRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AddressPath(Table<O> path, ForeignKey<O, AddressRecord> childPath, InverseForeignKey<O, AddressRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AddressPath(Name alias, Table<AddressRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AddressPath as(String alias) {
            return new AddressPath(DSL.name(alias), this);
        }

        @Override
        public AddressPath as(Name alias) {
            return new AddressPath(alias, this);
        }

        @Override
        public AddressPath as(Table<?> alias) {
            return new AddressPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sakila.SAKILA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ADDRESS_IDX_FK_CITY_ID);
    }

    @Override
    public Identity<AddressRecord, Integer> getIdentity() {
        return (Identity<AddressRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AddressRecord> getPrimaryKey() {
        return Keys.KEY_ADDRESS_PRIMARY;
    }

    @Override
    public List<ForeignKey<AddressRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ADDRESS_CITY);
    }

    private transient CityPath _city;

    /**
     * Get the implicit join path to the <code>sakila.city</code> table.
     */
    public CityPath city() {
        if (_city == null)
            _city = new CityPath(this, Keys.FK_ADDRESS_CITY, null);

        return _city;
    }

    private transient CustomerPath _customer;

    /**
     * Get the implicit to-many join path to the <code>sakila.customer</code>
     * table
     */
    public CustomerPath customer() {
        if (_customer == null)
            _customer = new CustomerPath(this, null, Keys.FK_CUSTOMER_ADDRESS.getInverseKey());

        return _customer;
    }

    private transient StaffPath _staff;

    /**
     * Get the implicit to-many join path to the <code>sakila.staff</code> table
     */
    public StaffPath staff() {
        if (_staff == null)
            _staff = new StaffPath(this, null, Keys.FK_STAFF_ADDRESS.getInverseKey());

        return _staff;
    }

    private transient StorePath _store;

    /**
     * Get the implicit to-many join path to the <code>sakila.store</code> table
     */
    public StorePath store() {
        if (_store == null)
            _store = new StorePath(this, null, Keys.FK_STORE_ADDRESS.getInverseKey());

        return _store;
    }

    @Override
    public TableField<AddressRecord, LocalDateTime> getRecordTimestamp() {
        return LAST_UPDATE;
    }

    @Override
    public AddressTable as(String alias) {
        return new AddressTable(DSL.name(alias), this);
    }

    @Override
    public AddressTable as(Name alias) {
        return new AddressTable(alias, this);
    }

    @Override
    public AddressTable as(Table<?> alias) {
        return new AddressTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressTable rename(String name) {
        return new AddressTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressTable rename(Name name) {
        return new AddressTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressTable rename(Table<?> name) {
        return new AddressTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AddressTable where(Condition condition) {
        return new AddressTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AddressTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AddressTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AddressTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AddressTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AddressTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AddressTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AddressTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AddressTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AddressTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
