/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.northcoder.sakila.jooq.Keys;
import org.northcoder.sakila.jooq.Sakila;
import org.northcoder.sakila.jooq.tables.FilmTable.FilmPath;
import org.northcoder.sakila.jooq.tables.records.LanguageRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LanguageTable extends TableImpl<LanguageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sakila.language</code>
     */
    public static final LanguageTable LANGUAGE = new LanguageTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LanguageRecord> getRecordType() {
        return LanguageRecord.class;
    }

    /**
     * The column <code>sakila.language.language_id</code>.
     */
    public final TableField<LanguageRecord, Integer> LANGUAGE_ID = createField(DSL.name("language_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sakila.language.name</code>.
     */
    public final TableField<LanguageRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CHAR(20).nullable(false), this, "");

    /**
     * The column <code>sakila.language.last_update</code>.
     */
    public final TableField<LanguageRecord, LocalDateTime> LAST_UPDATE = createField(DSL.name("last_update"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private LanguageTable(Name alias, Table<LanguageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LanguageTable(Name alias, Table<LanguageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sakila.language</code> table reference
     */
    public LanguageTable(String alias) {
        this(DSL.name(alias), LANGUAGE);
    }

    /**
     * Create an aliased <code>sakila.language</code> table reference
     */
    public LanguageTable(Name alias) {
        this(alias, LANGUAGE);
    }

    /**
     * Create a <code>sakila.language</code> table reference
     */
    public LanguageTable() {
        this(DSL.name("language"), null);
    }

    public <O extends Record> LanguageTable(Table<O> path, ForeignKey<O, LanguageRecord> childPath, InverseForeignKey<O, LanguageRecord> parentPath) {
        super(path, childPath, parentPath, LANGUAGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LanguagePath extends LanguageTable implements Path<LanguageRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LanguagePath(Table<O> path, ForeignKey<O, LanguageRecord> childPath, InverseForeignKey<O, LanguageRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LanguagePath(Name alias, Table<LanguageRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LanguagePath as(String alias) {
            return new LanguagePath(DSL.name(alias), this);
        }

        @Override
        public LanguagePath as(Name alias) {
            return new LanguagePath(alias, this);
        }

        @Override
        public LanguagePath as(Table<?> alias) {
            return new LanguagePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sakila.SAKILA;
    }

    @Override
    public Identity<LanguageRecord, Integer> getIdentity() {
        return (Identity<LanguageRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LanguageRecord> getPrimaryKey() {
        return Keys.KEY_LANGUAGE_PRIMARY;
    }

    private transient FilmPath _fkFilmLanguage;

    /**
     * Get the implicit to-many join path to the <code>sakila.film</code> table,
     * via the <code>fk_film_language</code> key
     */
    public FilmPath fkFilmLanguage() {
        if (_fkFilmLanguage == null)
            _fkFilmLanguage = new FilmPath(this, null, Keys.FK_FILM_LANGUAGE.getInverseKey());

        return _fkFilmLanguage;
    }

    private transient FilmPath _fkFilmLanguageOriginal;

    /**
     * Get the implicit to-many join path to the <code>sakila.film</code> table,
     * via the <code>fk_film_language_original</code> key
     */
    public FilmPath fkFilmLanguageOriginal() {
        if (_fkFilmLanguageOriginal == null)
            _fkFilmLanguageOriginal = new FilmPath(this, null, Keys.FK_FILM_LANGUAGE_ORIGINAL.getInverseKey());

        return _fkFilmLanguageOriginal;
    }

    @Override
    public TableField<LanguageRecord, LocalDateTime> getRecordTimestamp() {
        return LAST_UPDATE;
    }

    @Override
    public LanguageTable as(String alias) {
        return new LanguageTable(DSL.name(alias), this);
    }

    @Override
    public LanguageTable as(Name alias) {
        return new LanguageTable(alias, this);
    }

    @Override
    public LanguageTable as(Table<?> alias) {
        return new LanguageTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LanguageTable rename(String name) {
        return new LanguageTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LanguageTable rename(Name name) {
        return new LanguageTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LanguageTable rename(Table<?> name) {
        return new LanguageTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LanguageTable where(Condition condition) {
        return new LanguageTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LanguageTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LanguageTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LanguageTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LanguageTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LanguageTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LanguageTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LanguageTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LanguageTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LanguageTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
