/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.northcoder.sakila.jooq.tables.ActorTable;
import org.northcoder.sakila.jooq.tables.AddressTable;
import org.northcoder.sakila.jooq.tables.CityTable;
import org.northcoder.sakila.jooq.tables.CustomerTable;
import org.northcoder.sakila.jooq.tables.FilmActorTable;
import org.northcoder.sakila.jooq.tables.FilmTable;
import org.northcoder.sakila.jooq.tables.FilmTextTable;
import org.northcoder.sakila.jooq.tables.InventoryTable;
import org.northcoder.sakila.jooq.tables.PaymentTable;
import org.northcoder.sakila.jooq.tables.RentalTable;
import org.northcoder.sakila.jooq.tables.StaffTable;
import org.northcoder.sakila.jooq.tables.StoreTable;


/**
 * A class modelling indexes of tables in sakila.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACTOR_IDX_ACTOR_LAST_NAME = Internal.createIndex(DSL.name("idx_actor_last_name"), ActorTable.ACTOR, new OrderField[] { ActorTable.ACTOR.LAST_NAME }, false);
    public static final Index CUSTOMER_IDX_FK_ADDRESS_ID = Internal.createIndex(DSL.name("idx_fk_address_id"), CustomerTable.CUSTOMER, new OrderField[] { CustomerTable.CUSTOMER.ADDRESS_ID }, false);
    public static final Index STAFF_IDX_FK_ADDRESS_ID = Internal.createIndex(DSL.name("idx_fk_address_id"), StaffTable.STAFF, new OrderField[] { StaffTable.STAFF.ADDRESS_ID }, false);
    public static final Index STORE_IDX_FK_ADDRESS_ID = Internal.createIndex(DSL.name("idx_fk_address_id"), StoreTable.STORE, new OrderField[] { StoreTable.STORE.ADDRESS_ID }, false);
    public static final Index ADDRESS_IDX_FK_CITY_ID = Internal.createIndex(DSL.name("idx_fk_city_id"), AddressTable.ADDRESS, new OrderField[] { AddressTable.ADDRESS.CITY_ID }, false);
    public static final Index CITY_IDX_FK_COUNTRY_ID = Internal.createIndex(DSL.name("idx_fk_country_id"), CityTable.CITY, new OrderField[] { CityTable.CITY.COUNTRY_ID }, false);
    public static final Index PAYMENT_IDX_FK_CUSTOMER_ID = Internal.createIndex(DSL.name("idx_fk_customer_id"), PaymentTable.PAYMENT, new OrderField[] { PaymentTable.PAYMENT.CUSTOMER_ID }, false);
    public static final Index RENTAL_IDX_FK_CUSTOMER_ID = Internal.createIndex(DSL.name("idx_fk_customer_id"), RentalTable.RENTAL, new OrderField[] { RentalTable.RENTAL.CUSTOMER_ID }, false);
    public static final Index FILM_ACTOR_IDX_FK_FILM_ID = Internal.createIndex(DSL.name("idx_fk_film_id"), FilmActorTable.FILM_ACTOR, new OrderField[] { FilmActorTable.FILM_ACTOR.FILM_ID }, false);
    public static final Index INVENTORY_IDX_FK_FILM_ID = Internal.createIndex(DSL.name("idx_fk_film_id"), InventoryTable.INVENTORY, new OrderField[] { InventoryTable.INVENTORY.FILM_ID }, false);
    public static final Index RENTAL_IDX_FK_INVENTORY_ID = Internal.createIndex(DSL.name("idx_fk_inventory_id"), RentalTable.RENTAL, new OrderField[] { RentalTable.RENTAL.INVENTORY_ID }, false);
    public static final Index FILM_IDX_FK_LANGUAGE_ID = Internal.createIndex(DSL.name("idx_fk_language_id"), FilmTable.FILM, new OrderField[] { FilmTable.FILM.LANGUAGE_ID }, false);
    public static final Index FILM_IDX_FK_ORIGINAL_LANGUAGE_ID = Internal.createIndex(DSL.name("idx_fk_original_language_id"), FilmTable.FILM, new OrderField[] { FilmTable.FILM.ORIGINAL_LANGUAGE_ID }, false);
    public static final Index PAYMENT_IDX_FK_STAFF_ID = Internal.createIndex(DSL.name("idx_fk_staff_id"), PaymentTable.PAYMENT, new OrderField[] { PaymentTable.PAYMENT.STAFF_ID }, false);
    public static final Index RENTAL_IDX_FK_STAFF_ID = Internal.createIndex(DSL.name("idx_fk_staff_id"), RentalTable.RENTAL, new OrderField[] { RentalTable.RENTAL.STAFF_ID }, false);
    public static final Index CUSTOMER_IDX_FK_STORE_ID = Internal.createIndex(DSL.name("idx_fk_store_id"), CustomerTable.CUSTOMER, new OrderField[] { CustomerTable.CUSTOMER.STORE_ID }, false);
    public static final Index STAFF_IDX_FK_STORE_ID = Internal.createIndex(DSL.name("idx_fk_store_id"), StaffTable.STAFF, new OrderField[] { StaffTable.STAFF.STORE_ID }, false);
    public static final Index CUSTOMER_IDX_LAST_NAME = Internal.createIndex(DSL.name("idx_last_name"), CustomerTable.CUSTOMER, new OrderField[] { CustomerTable.CUSTOMER.LAST_NAME }, false);
    public static final Index INVENTORY_IDX_STORE_ID_FILM_ID = Internal.createIndex(DSL.name("idx_store_id_film_id"), InventoryTable.INVENTORY, new OrderField[] { InventoryTable.INVENTORY.STORE_ID, InventoryTable.INVENTORY.FILM_ID }, false);
    public static final Index FILM_IDX_TITLE = Internal.createIndex(DSL.name("idx_title"), FilmTable.FILM, new OrderField[] { FilmTable.FILM.TITLE }, false);
    public static final Index FILM_TEXT_IDX_TITLE_DESCRIPTION = Internal.createIndex(DSL.name("idx_title_description"), FilmTextTable.FILM_TEXT, new OrderField[] { FilmTextTable.FILM_TEXT.TITLE, FilmTextTable.FILM_TEXT.DESCRIPTION }, false);
}
