/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.northcoder.sakila.jooq.tables.ActorInfoTable;
import org.northcoder.sakila.jooq.tables.ActorTable;
import org.northcoder.sakila.jooq.tables.AddressTable;
import org.northcoder.sakila.jooq.tables.CategoryTable;
import org.northcoder.sakila.jooq.tables.CityTable;
import org.northcoder.sakila.jooq.tables.CountryTable;
import org.northcoder.sakila.jooq.tables.CustomerListTable;
import org.northcoder.sakila.jooq.tables.CustomerTable;
import org.northcoder.sakila.jooq.tables.FilmActorTable;
import org.northcoder.sakila.jooq.tables.FilmCategoryTable;
import org.northcoder.sakila.jooq.tables.FilmListTable;
import org.northcoder.sakila.jooq.tables.FilmTable;
import org.northcoder.sakila.jooq.tables.FilmTextTable;
import org.northcoder.sakila.jooq.tables.InventoryTable;
import org.northcoder.sakila.jooq.tables.LanguageTable;
import org.northcoder.sakila.jooq.tables.NicerButSlowerFilmListTable;
import org.northcoder.sakila.jooq.tables.PaymentTable;
import org.northcoder.sakila.jooq.tables.RentalTable;
import org.northcoder.sakila.jooq.tables.SalesByFilmCategoryTable;
import org.northcoder.sakila.jooq.tables.SalesByStoreTable;
import org.northcoder.sakila.jooq.tables.StaffListTable;
import org.northcoder.sakila.jooq.tables.StaffTable;
import org.northcoder.sakila.jooq.tables.StoreTable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sakila extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sakila</code>
     */
    public static final Sakila SAKILA = new Sakila();

    /**
     * The table <code>sakila.actor</code>.
     */
    public final ActorTable ACTOR = ActorTable.ACTOR;

    /**
     * VIEW
     */
    public final ActorInfoTable ACTOR_INFO = ActorInfoTable.ACTOR_INFO;

    /**
     * The table <code>sakila.address</code>.
     */
    public final AddressTable ADDRESS = AddressTable.ADDRESS;

    /**
     * The table <code>sakila.category</code>.
     */
    public final CategoryTable CATEGORY = CategoryTable.CATEGORY;

    /**
     * The table <code>sakila.city</code>.
     */
    public final CityTable CITY = CityTable.CITY;

    /**
     * The table <code>sakila.country</code>.
     */
    public final CountryTable COUNTRY = CountryTable.COUNTRY;

    /**
     * The table <code>sakila.customer</code>.
     */
    public final CustomerTable CUSTOMER = CustomerTable.CUSTOMER;

    /**
     * VIEW
     */
    public final CustomerListTable CUSTOMER_LIST = CustomerListTable.CUSTOMER_LIST;

    /**
     * The table <code>sakila.film</code>.
     */
    public final FilmTable FILM = FilmTable.FILM;

    /**
     * The table <code>sakila.film_actor</code>.
     */
    public final FilmActorTable FILM_ACTOR = FilmActorTable.FILM_ACTOR;

    /**
     * The table <code>sakila.film_category</code>.
     */
    public final FilmCategoryTable FILM_CATEGORY = FilmCategoryTable.FILM_CATEGORY;

    /**
     * VIEW
     */
    public final FilmListTable FILM_LIST = FilmListTable.FILM_LIST;

    /**
     * The table <code>sakila.film_text</code>.
     */
    public final FilmTextTable FILM_TEXT = FilmTextTable.FILM_TEXT;

    /**
     * The table <code>sakila.inventory</code>.
     */
    public final InventoryTable INVENTORY = InventoryTable.INVENTORY;

    /**
     * The table <code>sakila.language</code>.
     */
    public final LanguageTable LANGUAGE = LanguageTable.LANGUAGE;

    /**
     * VIEW
     */
    public final NicerButSlowerFilmListTable NICER_BUT_SLOWER_FILM_LIST = NicerButSlowerFilmListTable.NICER_BUT_SLOWER_FILM_LIST;

    /**
     * The table <code>sakila.payment</code>.
     */
    public final PaymentTable PAYMENT = PaymentTable.PAYMENT;

    /**
     * The table <code>sakila.rental</code>.
     */
    public final RentalTable RENTAL = RentalTable.RENTAL;

    /**
     * VIEW
     */
    public final SalesByFilmCategoryTable SALES_BY_FILM_CATEGORY = SalesByFilmCategoryTable.SALES_BY_FILM_CATEGORY;

    /**
     * VIEW
     */
    public final SalesByStoreTable SALES_BY_STORE = SalesByStoreTable.SALES_BY_STORE;

    /**
     * The table <code>sakila.staff</code>.
     */
    public final StaffTable STAFF = StaffTable.STAFF;

    /**
     * VIEW
     */
    public final StaffListTable STAFF_LIST = StaffListTable.STAFF_LIST;

    /**
     * The table <code>sakila.store</code>.
     */
    public final StoreTable STORE = StoreTable.STORE;

    /**
     * No further instances allowed
     */
    private Sakila() {
        super("sakila", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ActorTable.ACTOR,
            ActorInfoTable.ACTOR_INFO,
            AddressTable.ADDRESS,
            CategoryTable.CATEGORY,
            CityTable.CITY,
            CountryTable.COUNTRY,
            CustomerTable.CUSTOMER,
            CustomerListTable.CUSTOMER_LIST,
            FilmTable.FILM,
            FilmActorTable.FILM_ACTOR,
            FilmCategoryTable.FILM_CATEGORY,
            FilmListTable.FILM_LIST,
            FilmTextTable.FILM_TEXT,
            InventoryTable.INVENTORY,
            LanguageTable.LANGUAGE,
            NicerButSlowerFilmListTable.NICER_BUT_SLOWER_FILM_LIST,
            PaymentTable.PAYMENT,
            RentalTable.RENTAL,
            SalesByFilmCategoryTable.SALES_BY_FILM_CATEGORY,
            SalesByStoreTable.SALES_BY_STORE,
            StaffTable.STAFF,
            StaffListTable.STAFF_LIST,
            StoreTable.STORE
        );
    }
}
