/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq;


import org.northcoder.sakila.jooq.tables.ActorInfoTable;
import org.northcoder.sakila.jooq.tables.ActorTable;
import org.northcoder.sakila.jooq.tables.AddressTable;
import org.northcoder.sakila.jooq.tables.CategoryTable;
import org.northcoder.sakila.jooq.tables.CityTable;
import org.northcoder.sakila.jooq.tables.CountryTable;
import org.northcoder.sakila.jooq.tables.CustomerListTable;
import org.northcoder.sakila.jooq.tables.CustomerTable;
import org.northcoder.sakila.jooq.tables.FilmActorTable;
import org.northcoder.sakila.jooq.tables.FilmCategoryTable;
import org.northcoder.sakila.jooq.tables.FilmListTable;
import org.northcoder.sakila.jooq.tables.FilmTable;
import org.northcoder.sakila.jooq.tables.FilmTextTable;
import org.northcoder.sakila.jooq.tables.InventoryTable;
import org.northcoder.sakila.jooq.tables.LanguageTable;
import org.northcoder.sakila.jooq.tables.NicerButSlowerFilmListTable;
import org.northcoder.sakila.jooq.tables.PaymentTable;
import org.northcoder.sakila.jooq.tables.RentalTable;
import org.northcoder.sakila.jooq.tables.SalesByFilmCategoryTable;
import org.northcoder.sakila.jooq.tables.SalesByStoreTable;
import org.northcoder.sakila.jooq.tables.StaffListTable;
import org.northcoder.sakila.jooq.tables.StaffTable;
import org.northcoder.sakila.jooq.tables.StoreTable;


/**
 * Convenience access to all tables in sakila.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>sakila.actor</code>.
     */
    public static final ActorTable ACTOR = ActorTable.ACTOR;

    /**
     * VIEW
     */
    public static final ActorInfoTable ACTOR_INFO = ActorInfoTable.ACTOR_INFO;

    /**
     * The table <code>sakila.address</code>.
     */
    public static final AddressTable ADDRESS = AddressTable.ADDRESS;

    /**
     * The table <code>sakila.category</code>.
     */
    public static final CategoryTable CATEGORY = CategoryTable.CATEGORY;

    /**
     * The table <code>sakila.city</code>.
     */
    public static final CityTable CITY = CityTable.CITY;

    /**
     * The table <code>sakila.country</code>.
     */
    public static final CountryTable COUNTRY = CountryTable.COUNTRY;

    /**
     * The table <code>sakila.customer</code>.
     */
    public static final CustomerTable CUSTOMER = CustomerTable.CUSTOMER;

    /**
     * VIEW
     */
    public static final CustomerListTable CUSTOMER_LIST = CustomerListTable.CUSTOMER_LIST;

    /**
     * The table <code>sakila.film</code>.
     */
    public static final FilmTable FILM = FilmTable.FILM;

    /**
     * The table <code>sakila.film_actor</code>.
     */
    public static final FilmActorTable FILM_ACTOR = FilmActorTable.FILM_ACTOR;

    /**
     * The table <code>sakila.film_category</code>.
     */
    public static final FilmCategoryTable FILM_CATEGORY = FilmCategoryTable.FILM_CATEGORY;

    /**
     * VIEW
     */
    public static final FilmListTable FILM_LIST = FilmListTable.FILM_LIST;

    /**
     * The table <code>sakila.film_text</code>.
     */
    public static final FilmTextTable FILM_TEXT = FilmTextTable.FILM_TEXT;

    /**
     * The table <code>sakila.inventory</code>.
     */
    public static final InventoryTable INVENTORY = InventoryTable.INVENTORY;

    /**
     * The table <code>sakila.language</code>.
     */
    public static final LanguageTable LANGUAGE = LanguageTable.LANGUAGE;

    /**
     * VIEW
     */
    public static final NicerButSlowerFilmListTable NICER_BUT_SLOWER_FILM_LIST = NicerButSlowerFilmListTable.NICER_BUT_SLOWER_FILM_LIST;

    /**
     * The table <code>sakila.payment</code>.
     */
    public static final PaymentTable PAYMENT = PaymentTable.PAYMENT;

    /**
     * The table <code>sakila.rental</code>.
     */
    public static final RentalTable RENTAL = RentalTable.RENTAL;

    /**
     * VIEW
     */
    public static final SalesByFilmCategoryTable SALES_BY_FILM_CATEGORY = SalesByFilmCategoryTable.SALES_BY_FILM_CATEGORY;

    /**
     * VIEW
     */
    public static final SalesByStoreTable SALES_BY_STORE = SalesByStoreTable.SALES_BY_STORE;

    /**
     * The table <code>sakila.staff</code>.
     */
    public static final StaffTable STAFF = StaffTable.STAFF;

    /**
     * VIEW
     */
    public static final StaffListTable STAFF_LIST = StaffListTable.STAFF_LIST;

    /**
     * The table <code>sakila.store</code>.
     */
    public static final StoreTable STORE = StoreTable.STORE;
}
