/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables.pojos;


import java.io.Serializable;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public record ActorInfo(
    Integer actorId,
    String firstName,
    String lastName,
    String filmInfo
) implements Serializable {

    private static final long serialVersionUID = 1L;

}
