/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.Year;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public record Film(
    Integer filmId,
    String title,
    String description,
    Year releaseYear,
    Integer languageId,
    Integer originalLanguageId,
    Byte rentalDuration,
    BigDecimal rentalRate,
    Short length,
    BigDecimal replacementCost,
    String rating,
    String specialFeatures,
    LocalDateTime lastUpdate
) implements Serializable {

    private static final long serialVersionUID = 1L;

}
