/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public record FilmList(
    Integer fid,
    String title,
    String description,
    String category,
    BigDecimal price,
    Short length,
    String rating,
    String actors
) implements Serializable {

    private static final long serialVersionUID = 1L;

}
