/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public record FilmText(
    Integer filmId,
    String title,
    String description
) implements Serializable {

    private static final long serialVersionUID = 1L;

}
