/*
 * This file is generated by jOOQ.
 */
package org.northcoder.sakila.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public record SalesByStore(
    String store,
    String manager,
    BigDecimal totalSales
) implements Serializable {

    private static final long serialVersionUID = 1L;

}
